### ISSUE TITLE
Callouts

### ISSUE THREAD

**Issue by Minus10Celcius** [Elevict/Shade-Sanctuary#2]
![image](https://github.com/user-attachments/assets/00ed80c6-b546-4778-ad53-d129d649a8af)

Maybe you'd want to color your gradient callout arrows?

**Comment by Elevict** [comment]
Thanks for reaching out.  The gradient callout arrows should be fixed right now. Let me know if it works now.

**Comment by Minus10Celcius** [comment]
> Thanks for reaching out. The gradient callout arrows should be fixed right now. Let me know if it works now.

Updated, but still no difference

![image](https://github.com/user-attachments/assets/916a8eba-a04f-4763-86f8-457730792b06)

**Comment by Elevict** [comment]
In a new default vault, the gradient callouts function (With or without the theme). I am assuming you are talking about the gradient headers and callouts snippet.

![image](https://github.com/user-attachments/assets/46041adc-1849-450f-b2bc-af3a32aa9056)

Can you please provide more information? What is the markdown you are writing to get the callout? Are you using the shade sanctuary theme alone or another theme as well (If another theme please specify)? Are there any other snippets you are using too? Please make sure you are getting the updated snippet [here](https://github.com/Elevict/Elevict-Snippets).

**Comment by Minus10Celcius** [comment]
updated snippet works!!
